dist: bionic
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.6'
    env: TOXENV=manifest
  - python: '3.6'
    env: TOXENV=docs
install:
- pip install tox
script:
- tox
notifications:
  email: false
deploy:
  provider: pypi
  user: spotify_alf
  password:
    secure: IMyOw5c15qHZIZt1c+VFYpSaJmRpAyqSjK9rZPwlij5L6NqqqUPUiuSuiivmIkIB+wcOtyaYPNu6w48qDQPa+todZUhCKFC9MN0yBqxdjw52Syd3bOT5ypGxFW9cY/Ijy9s3HDoRmXk9Fe6B6c+ArvzE686dX4Di+9KD1PA3PAZW32tJIEaZAjLdDwnLKNplgU3v4pZKnf2Yqzsd82PRYawMRoUfP6TG4DrBSLNdFI0U1TWBBJd3iswGcHwcu8Xc8raZuyI2NzxXxwy1Myi8CoM1U1xvv/vzLbjmZbeHm0Ap1IUmbX7/LDa8dMFFDt8mAVnLwGovhA7dbZHOlUVY7Vh7LoH16dQA6JgGXsNGoFBo+I0KQvRqZre1X25NiUO85/a2CoIkFktEibSjLElYJ5NQP8iGYLpujXaKDU6klAIW6s6qm4EkKwJJMfGx0FURqdSe71HegMufFxmGqoUwz8KMso0GsuhsBqztllJZxbwkau9K1we+sbxkgxSOOis0QLGqZd/i5fNiw/BoLjS1LxF65uizllKsNJZnoATbVFJSdq2K/O+MYoaY6fotG2ZsDHJS/KZw/c2zj+TWy9tPeSifv4DskMSC1xyzYZhrvXytNZ1Y2NdvGHhMmVOHfjaqu2ahz1Qh4TlsMMlN8KK31a4fmkwxtiSMTgBbP36hEtE=
  on:
    tags: true
    branch: master
    condition: $TOXENV = py36
  distributions: sdist bdist_wheel
